system:
  host: "0.0.0.0"
  port: 5001
  env: debug
  #env: release

#日志配置
logger:
  level: info
  prefix: '[gin-admin-api]'
  director: logger
  show_line: true
  log_in_console: true

#数据库配置 mysql
mysql:
  host: 39.106.0.29
  port: 33060
  db: gin_blog
  username: root
  password: Yjk#2u7*W5
  log_level: dev
  charset: utf8
  maxIdle: 50  #最大连接数
  maxOpen: 150 #？？？

#redis配置
redis:
  address: 39.106.0.29:6379
  password: Yjk#2u7*W5
  db: 0

#token 配置
token:
  headers: Bearer
  expireTime: 24
  secret: gin-admin-api
  issuer: admin

#UpLoad 配置
upload:
  path: "public/uploaded"      # 本地文件访问路径: OssType="local" 生效
